FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

COPY . .

RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 9393

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9393"]